export const QueryKeys = {
  ME: 'me',
  AREA_OF_LAW: 'area_of_law',
  ACTIVE_CHATS: 'active_chats',
  NOTIFICATION: 'notification',
  IN_ACTIVE_CHATS: 'inactive_chats',
  COMMON_CASES: 'common_cases',
  LAWYERS: 'lawyers',
  FEEDS: 'feeds',
  FEEDS_SEARCH: 'feeds_search',
  MY_FEEDS: 'my_feeds',
  MY_CLIENTS: 'my_clients',
  FEEDS_BY_ID: 'feeds_by_id',
  SUBSCRIPTION_LIST: 'subscription_list',
  STATE: 'state',
  CITY_OF_STATE: 'city_of_state',
  MY_POCKET: 'my_pocket',
  MY_POCKET_SHARED_FILE: 'my_pocket_shared_files',
  REVIEW_RATE_LIST: 'rate_review_list',
  REVIEW_RATE_LIST_BY_ID: 'rate_review_list_by_id',
  Blocked_USERS_LIST: 'blocked_user_list',
  DASHBOARD_LIST: 'dashboard_list',
};
